const GRID_SIZE = 8, STORAGE_KEY = "rice-sim-state-v2";
const phaseOrder = ["empty","seed","planted","growing","heading","ripening","harvest"];
const phaseColor = {empty:"#dce9df",seed:"#b8d8b8",planted:"#8ecf8d",growing:"#57b96a",heading:"#8bc34a",ripening:"#d7b857",harvest:"#a98e3f"};
const specialSeeds = {gold_seed:{growth:1.4,quality:1,resist:1},rainbow_seed:{growth:1,quality:1.35,resist:1},strong_seed:{growth:1,quality:1,resist:1.35},normal:{growth:1,quality:1,resist:1}};
const state={grid:[],water:.5,time:0,score:0,bpm:120,combo:0,lastTap:0,nextBeat:0,timing:"-",weather:"Stable",eventMultiplier:1,specialChance:.05,inventoryRice:0,harvestStats:[],scores:{rhythm:0,placement:0,growth:0,product:0},logs:[]};
const $=id=>document.getElementById(id); const fieldEl=$("field");
function tile(i){return {index:i,phase:"empty",progress:0,quality:1,seedType:"normal"};}
function log(type,d={}){state.logs.push({ts:new Date().toISOString(),day:+state.time.toFixed(2),type,...d}); if(state.logs.length>600)state.logs.shift(); renderLogs();}
function renderLogs(){const h="timestamp,day,type,tile,from,to,seed,timing,combo,water,rhythm,placement,growth,product,total\n"; const rows=state.logs.map(l=>[l.ts,l.day,l.type,l.tile??"",l.from??"",l.to??"",l.seed??"",l.timing??"",l.combo??"",l.water??state.water,state.scores.rhythm,state.scores.placement,state.scores.growth,state.scores.product,totalScore()].join(",")); $("logOutput").value=h+rows.join("\n");}
function totalScore(){return state.scores.rhythm+state.scores.placement+state.scores.growth+state.scores.product;}
function densityAt(i){const x=i%GRID_SIZE,y=Math.floor(i/GRID_SIZE);let n=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=GRID_SIZE||ny>=GRID_SIZE)continue;const t=state.grid[ny*GRID_SIZE+nx];if(t.phase!=="empty"&&t.phase!=="harvest")n++;}return n;}
function judgeTiming(now){const beat=60/state.bpm; const offset=Math.abs((now-state.nextBeat)%beat); const d=Math.min(offset,beat-offset); if(d<0.07)return"perfect"; if(d<0.16)return"good"; return"miss";}
function onRhythmTap(){const now=performance.now()/1000; if(!state.nextBeat)state.nextBeat=now; const j=judgeTiming(now); state.timing=j; if(j==="miss"){state.combo=0;state.scores.rhythm=Math.max(0,state.scores.rhythm-5);} else {state.combo++; state.scores.rhythm+=j==="perfect"?20:10;} state.specialChance=Math.min(.45,.05+state.combo*0.02); $("timingText").textContent=`Timing: ${j} | Combo: ${state.combo}`; log("rhythm_tap",{timing:j,combo:state.combo}); renderHUD();}
function pickSeed(){if(Math.random()>state.specialChance)return"normal"; const r=Math.random(); return r<.34?"gold_seed":r<.67?"rainbow_seed":"strong_seed";}
function plant(i){const t=state.grid[i]; if(!t||t.phase!=="empty")return; const seed=pickSeed(); t.phase="seed";t.progress=0;t.seedType=seed; t.quality=Math.max(.6,1.2-densityAt(i)*.08)*specialSeeds[seed].quality; log("plant",{tile:i,to:"seed",seed,timing:state.timing,combo:state.combo}); renderField();}
function updateSynergy(){let bonus=0;for(let r=0;r<GRID_SIZE;r++){const row=state.grid.slice(r*GRID_SIZE,r*GRID_SIZE+GRID_SIZE); if(row.every(t=>t.phase!=="empty"&&t.phase!=="harvest"))bonus+=12;} for(let y=0;y<GRID_SIZE-1;y++)for(let x=0;x<GRID_SIZE-1;x++){const ids=[y*GRID_SIZE+x,y*GRID_SIZE+x+1,(y+1)*GRID_SIZE+x,(y+1)*GRID_SIZE+x+1]; if(ids.every(i=>!['empty','harvest'].includes(state.grid[i].phase)))bonus+=5;} let d1=true,d2=true; for(let i=0;i<GRID_SIZE;i++){if(["empty","harvest"].includes(state.grid[i*GRID_SIZE+i].phase))d1=false; if(["empty","harvest"].includes(state.grid[i*GRID_SIZE+(GRID_SIZE-1-i)].phase))d2=false;} if(d1)bonus+=14;if(d2)bonus+=14; state.scores.placement=bonus;}
function harvest(i){const t=state.grid[i]; if(!t||t.phase!=="ripening")return; const waterQ=1-Math.abs(.65-state.water); const seedBoost=specialSeeds[t.seedType]; const points=Math.max(1,Math.round(70*t.quality*waterQ*seedBoost.quality)); state.scores.growth+=points; state.inventoryRice+=Math.max(1,Math.round(points/10)); state.harvestStats.push({quality:t.quality,seed:t.seedType,water:state.water}); t.phase="harvest"; t.progress=0; log("harvest",{tile:i,seed:t.seedType}); renderHUD(); renderField();}
function tick(dt){state.time+=dt; if(Math.floor(state.time*10)%100===0){const r=Math.random(); state.eventMultiplier=r<.16?1.3:r<.3?.75:1; state.weather=state.eventMultiplier>1?"Rain burst":state.eventMultiplier<1?"Heat stress":"Stable";} state.grid.forEach((t,i)=>{if(["empty","harvest","ripening"].includes(t.phase))return; const seed=specialSeeds[t.seedType]; const d=Math.max(.55,1-densityAt(i)*.06); const w=1-Math.abs(.62-state.water)*1.2; const bad=state.eventMultiplier<1?seed.resist:1; t.progress+=dt*.08*d*Math.max(.3,w)*state.eventMultiplier*seed.growth*bad; if(t.progress>=1){const from=t.phase; t.phase=phaseOrder[Math.min(phaseOrder.indexOf(t.phase)+1,phaseOrder.length-1)]; t.progress=0; log("phase_change",{tile:i,from,to:t.phase,seed:t.seedType});}}); updateSynergy(); renderHUD(); renderField();}
function craft(product){if(!state.harvestStats.length)return; const avg=state.harvestStats.reduce((a,b)=>a+b.quality,0)/state.harvestStats.length; const base={onigiri:60,bento:90,sake:110,teishoku:130}[product]||60; const need={onigiri:3,bento:5,sake:7,teishoku:8}[product]||3; if(state.inventoryRice<need){$("craftResult").textContent=`Need ${need} rice (have ${state.inventoryRice}).`; return;} state.inventoryRice-=need; const p=Math.round(base*avg*(1+state.scores.placement/200)); state.scores.product+=p; $("craftResult").textContent=`${product} crafted! quality ${p}`; log("craft",{to:product,score:p}); renderHUD();}
function renderField(){fieldEl.innerHTML=state.grid.map(t=>`<button class="tile ${(t.phase==='growing'||t.phase==='heading')?'growing-anim':''}" data-i="${t.index}" style="background:${phaseColor[t.phase]};"></button>`).join("");}
function renderHUD(){$("waterValue").textContent=state.water.toFixed(2);$("bpmValue").textContent=String(state.bpm);$("weatherText").textContent=`Weather: ${state.weather}`;$("scoreBoard").innerHTML=`<div class='score-card'>Rhythm: ${state.scores.rhythm}</div><div class='score-card'>Placement: ${state.scores.placement}</div><div class='score-card'>Growth: ${state.scores.growth}</div><div class='score-card'>Product: ${state.scores.product}</div><div class='score-card'>Total: ${totalScore()}</div><div class='score-card'>Rice: ${state.inventoryRice}</div>`;}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));log("save_state");}
function load(){const raw=localStorage.getItem(STORAGE_KEY); state.grid=Array.from({length:GRID_SIZE*GRID_SIZE},(_,i)=>tile(i)); if(!raw)return; try{const p=JSON.parse(raw); Object.assign(state,p); if(!Array.isArray(state.grid)||state.grid.length!==64)throw Error();}catch{}}
function bind(){let drag=false,harvestMode=false; fieldEl.addEventListener('pointerdown',e=>{drag=true;harvestMode=e.shiftKey;act(e.target)}); fieldEl.addEventListener('pointermove',e=>{if(!drag)return;act(document.elementFromPoint(e.clientX,e.clientY));});['pointerup','pointercancel','pointerleave'].forEach(ev=>fieldEl.addEventListener(ev,()=>{drag=false;harvestMode=false;})); fieldEl.addEventListener('touchstart',e=>{if(e.touches.length>1)harvestMode=true;}); function act(t){const i=Number(t?.dataset?.i); if(Number.isNaN(i))return; harvestMode?harvest(i):plant(i);} $("waterSlider").addEventListener('input',e=>{state.water=+e.target.value;log('water_change',{water:state.water});renderHUD();}); $("bpmSlider").addEventListener('input',e=>{state.bpm=+e.target.value;log('bpm_change');renderHUD();}); $("rhythmTapBtn").addEventListener('click',onRhythmTap); document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();onRhythmTap();}}); document.querySelectorAll('.craftBtn').forEach(b=>b.addEventListener('click',()=>craft(b.dataset.product))); $("saveBtn").addEventListener('click',save); $("exportJsonBtn").addEventListener('click',()=>download('rice-sim-result.json',JSON.stringify(state,null,2),'application/json')); $("exportCsvBtn").addEventListener('click',()=>download('rice-sim-log.csv',$("logOutput").value,'text/csv')); $("resetBtn").addEventListener('click',()=>{localStorage.removeItem(STORAGE_KEY);location.reload();});}
function download(name,text,type){const b=new Blob([text],{type});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function init(){load();bind();renderHUD();renderField();renderLogs();log('session_start');setInterval(()=>tick(.1),300);setInterval(save,5000);} init();
